Repository WoodNeck/mxm, pull requests merged in 2018-06, with the labels that each got.

#50 [FE] All MxMs 페이지에서 MxM status 변화 추가
  src/components/AllMxMs.vue
  src/store/modules/allMxMs.js
  src/store/types.js
  vuedj/settings.py
Labels: enhancement, frontend

#49 로그인 페이지 구현
  app/views.py
  src/components/Navbar.vue
  templates/index.html
  templates/login.html
  vuedj/settings.py
  vuedj/urls.py
Labels: backend, enhancement, frontend

#61 [FE] All Clothes tag filter 추가
  src/components/AllClothes.vue
  src/store/modules/allClothes.js
  src/store/modules/allMxMs.js
  test/unit/specs/AllClothes.spec.js
Labels: enhancement, frontend

#60 Cloth Registration Page 구현
  .gitignore
  app/migrations/0001_initial.py
  app/migrations/__init__.py
  app/migrations/tag_initial.py
  db.sqlite3
  deploy.sh
  package-lock.json
  package.json
  src/App.vue
  src/components/Navbar.vue
  src/components/NewClothes.vue
  src/store/modules/navbar.js
  src/store/modules/newClothes.js
  src/store/types.js
  templates/index.html
  vuedj/settings.py
Labels: enhancement, frontend

#65 MxM Detail 페이지 구현 + UI 업데이트
  app/migrations/0001_initial.py
  app/migrations/db_initial.py
  app/models.py
  app/serializers.py
  deploy.sh
  package-lock.json
  package.json
  src/components/AllMxMs.vue
  src/components/MxMDetail.vue
  src/router/index.js
Labels: backend, enhancement, frontend

#68 [FE] All MxM user 정보 추가
  package-lock.json
  src/components/AllMxMs.vue
  src/store/index.js
  src/store/modules/allMxMs.js
  src/store/types.js
  test/unit/specs/AllClothes.spec.js
  test/unit/specs/AllMxMs.spec.js
Labels: enhancement, frontend

#67 [FE] fix mxm plaza detail
  app/models.py
  app/serializers.py
  src/components/MxMPlazaDetail.vue
  src/store/index.js
  src/store/modules/MxMPlazaDetail.js
  src/store/types.js
Labels: enhancement, frontend

#69 New Clothes 페이지 UI 변경
  src/components/NewClothes.vue
  templates/index.html
Labels: UI, enhancement, frontend
