Repository WoodNeck/mxm, pull requests merged in 2018-05, with the labels that each got.

#20 fix(be): corsheaders setting
  vuedj/settings.py
Labels: backend

#18 Fix deploy.sh
  app/views.py
  format_index_html.py
  requirements.txt
  vuedj/settings.py
  vuedj/urls.py
Labels: backend, bug

#21 fix(be): change url naming to /api/*
  vuedj/settings.py
  vuedj/urls.py
Labels: backend

#25 [FE] All MxMs 페이지 추가
  src/components/AllClothes.vue
  src/components/AllMxMs.vue
  test/unit/specs/AllMxMs.spec.js
  test/unit/specs/Closet.spec.js
  test/unit/specs/ClothesDetail.spec.js
Labels: enhancement, frontend

#38 feat(be): tag auto-initialization at db migration
  app/migrations/tag_initial.py
  app/tags.txt
Labels: backend, enhancement

#40 backend test 추가
  app/constants.py
  app/tests.py
  app/views.py
  media/jean.jpeg
  requirements.txt
Labels: backend, enhancement

#41 [FE] clothes detail 페이지 추가
  src/components/AllClothes.vue
  src/components/ClothesDetail.vue
  src/router/index.js
  src/store/index.js
  src/store/modules/clothesDetail.js
  src/store/types.js
  test/unit/specs/AllMxMs.spec.js
  test/unit/specs/ClothesDetail.spec.js
Labels: enhancement, frontend
